export default {
  menuItems: [
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      iamgeUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageurl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      Price: "",
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imaegUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
    {
      category: "",
      description: "",
      imageUrl: "",
      itemId: "",
      name: "",
      price: "",
    },
  ],
  orders: [
    {
      orderId: "ORD1253",
      staff: {
        contactInfo: "alice@example.com",
        name: "Alice",
        role: "Waitress",
        staffId: "S1",
      },
      table: {
        capacity: 4,
        locationDescription: "Near window",
        tableId: "T1",
      },
      status: "Pending",
      timeStamp: "2024-06-12 19:15:00",
      items: [
        {
          kotId: "K001", // Unique identifier for the KOT item
          menuItem: "M001", // Reference to the MenuItem data class
          quantity: "2",
          status: "Pending",
          specialInstructions: "No Onion",
        },
        {
          kotId: "K001", // Unique identifier for the KOT item
          menuItem: "M004", // Reference to the MenuItem data class
          quantity: "2",
          status: "Pending",
          specialInstructions: "No Onion",
        },
        {
          kotId: "K001", // Unique identifier for the KOT item
          menuItem: "M003", // Reference to the MenuItem data class
          quantity: "2",
          status: "Pending",
          specialInstructions: "No Onion",
        },
      ],
    },
    {
      orderId: "ORD1280",
      staff: {
        contactInfo: "bob@example.com",
        name: "Bob",
        role: "Chef",
        staffId: "S2",
      },
      status: "Pending",
      table: {
        capacity: 2,
        locationDescription: "Patio",
        tableId: "T2",
      },
      timeStamp: "2024-06-12 19:15:00",
      items: [
        {
          kotId: "K002", // Unique identifier for the KOT item
          menuItem: "M002", // Reference to the MenuItem data class
          quantity: "3",
          status: "Pending",
          specialInstructions: "No Onion",
        },
        {
          kotId: "K002", // Unique identifier for the KOT item
          menuItem: "M002", // Reference to the MenuItem data class
          quantity: "1",
          status: "Pending",
          specialInstructions: "No Onion",
        },
        {
          kotId: "K002", // Unique identifier for the KOT item
          menuItem: "M002", // Reference to the MenuItem data class
          quantity: "4",
          status: "Pending",
          specialInstructions: "No Onion",
        },
      ],
    },
    {
      orderId: "ORD7058",
      staff: {
        contactInfo: "charlie@example.com",
        name: "Charlie",
        role: "Manager",
        staffId: "S3",
      },
      table: {
        capacity: 6,
        locationDescription: "Private booth",
        tableId: "T3",
      },
      timeStamp: "2024-06-12 19:15:00",
    },
    {
      orderId: "ORD1065",
      staff: {
        contactInfo: "david@example.com",
        name: "David",
        role: "Bartender",
        staffId: "S4",
      },
      table: {
        capacity: 8,
        locationDescription: "Center of the restaurant",
        tableId: "T4",
      },
      timeStamp: "2024-06-12 19:15:00",
    },
    {
      orderId: "ORD1459",
      staff: {
        contactInfo: "eve@example.com",
        name: "Eve",
        role: "Hostess",
        staffId: "S5",
      },
      table: {
        capacity: 2,
        locationDescription: "Bar counter",
        tableId: "T5",
      },
      timeStamp: "2024-06-12 19:15:00",
    },
    {
      orderId: "ORD3559",
      staff: {
        contactInfo: "frank@example.com",
        name: "Frank",
        role: "Waiter",
        staffId: "S6",
      },
      table: {
        capacity: 4,
        locationDescription: "Outdoor",
        tableId: "T6",
      },
      timeStamp: "2024-06-12 19:15:00",
    },
    {
      orderId: "ORD5854",
      staff: {
        contactInfo: "grace@example.com",
        name: "Grace",
        role: "Chef Assistant",
        staffId: "S7",
      },
      table: {
        capacity: 10,
        locationDescription: "VIP section",
        tableId: "T7",
      },
      timeStamp: "2024-06-12 19:15:00",
    },
    {
      orderId: "",
      staff: {
        contactInfo: "",
        name: "",
        role: "",
        staffId: "",
      },
      table: {
        capacity: "",
        locationDescription: "",
        tableId: "",
      },
      timeStamp: "",
    },
    {
      orderId: "",
      staff: {
        contactInfo: "",
        name: "",
        role: "",
        staffId: "",
      },
      table: {
        capacity: "",
        locationDescription: "",
        tableId: "",
      },
      timeStamp: "",
    },
    {
      orderId: "",
      staff: {
        contactInfo: "",
        name: "",
        role: "",
        staffId: "",
      },
      table: {
        capacity: "",
        locationDescription: "",
        tableId: "",
      },
      timeStamp: "",
    },
    {
      orderId: "",
      staff: {
        contactInfo: "",
        name: "",
        role: "",
        staffId: "",
      },
      table: {
        capacity: "",
        locationDescription: "",
        tableId: "",
      },
      timeStamp: "",
    },
    {
      orderId: "",
      staff: {
        contactInfo: "",
        name: "",
        role: "",
        staffId: "",
      },
      table: {
        capacity: "",
        locationDescription: "",
        tableId: "",
      },
      timeStamp: "",
    },
    {
      orderId: "",
      staff: {
        contactInfo: "",
        name: "",
        role: "",
        staffId: "",
      },
      table: {
        capacity: "",
        locationDescription: "",
        tableId: "",
      },
      timeStamp: "",
    },
    {
      orderId: "",
      staff: {
        contactInfo: "",
        name: "",
        role: "",
        staffId: "",
      },
      table: {
        capacity: "",
        locationDescription: "",
        tableId: "",
      },
      timeStamp: "",
    },
    {
      orderId: "",
      staff: {
        contactInfo: "",
        name: "",
        role: "",
        staffId: "",
      },
      table: {
        capacity: "",
        locationDescription: "",
        tableId: "",
      },
      timeStamp: "",
    },
    {
      orderId: "",
      staff: {
        contactInfo: "",
        name: "",
        role: "",
        staffId: "",
      },
      table: {
        capacity: "",
        locationDescription: "",
        tableId: "",
      },
      timeStamp: "",
    },
    {
      orderId: "",
      staff: {
        contactInfo: "",
        name: "",
        role: "",
        staffId: "",
      },
      table: {
        capacity: "",
        locationDescription: "",
        tableId: "",
      },
      timeStamp: "",
    },
    {
      orderId: "",
      staff: {
        conatctInfo: "",
        name: "",
        role: "",
        staffId: "",
      },
      table: {
        capacity: "",
        locationDescription: "",
        tableId: "",
      },
      timeStamp: "",
    },
    {
      orderId: "",
      staff: {
        contactInfo: "",
        name: "",
        role: "",
        staffId: "",
      },
      table: {
        capacity: "",
        locationDescription: "",
        tableId: "",
      },
      timeStamp: "",
    },
    {
      orderId: "",
      staff: {
        contactInfo: "",
        name: "",
        role: "",
        staffId: "",
      },
      table: {
        capacity: "",
        locationDescription: "",
        tableId: "",
      },
      timeStamp: "",
    },
    {
      orderId: "",
      staff: {
        contactInfo: "",
        name: "",
        role: "",
        staffId: "",
      },
      table: {
        capacity: "",
        locationDescription: "",
        tableId: "",
      },
      timeStamp: "",
    },
    {
      orderId: "",
      staff: {
        contactInfo: "",
        name: "",
        role: "",
        staffId: "",
      },
      table: {
        capacity: "",
        locationDescription: "",
        tableId: "",
      },
      timeStamp: "",
    },
    {
      orderId: "",
      staff: {
        contactInfo: "",
        name: "",
        role: "",
        staffId: "",
      },
      table: {
        capacity: "",
        locationDescription: "",
        tableId: "",
      },
      timeStamp: "",
    },
    {
      orderId: "",
      staff: {
        contactInfo: "",
        name: "",
        role: "",
        staffId: "",
      },
      table: {
        capacity: "",
        locationDescription: "",
        tableId: "",
      },
      timeStamp: "",
    },
    {
      orderId: "",
      staff: {
        contactInfo: "",
        name: "",
        role: "",
        staffId: "",
      },
      table: {
        capacity: "",
        locationDescription: "",
        tableId: "",
      },
      timeStamp: "",
    },
    {
      orderId: "",
      staff: {
        contactInfo: "",
        name: "",
        role: "",
        staffId: "",
      },
      table: {
        capacity: "",
        locationDescription: "",
        tableId: "",
      },
      timeStamp: "",
    },
  ],
};
